### ISSUE TITLE
Cannot download the plugin

### ISSUE THREAD

**Issue by YazeedFares** [Telerik-Verified-Plugins/WKWebView#18]
SyntaxError: Unexpected token <
    at Object.parse (native)
    at Object.get_platform_json (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/config-changes.js:461:31)
    at isPluginInstalled (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:247:42)
    at runInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:271:9)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:81:16
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:810:14
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)

**Comment by erperejildo** [comment]
What was the solution?
I have the same problem

**Comment by timmil** [comment]
I would also like to know how it was resolved!  Please help out @YazeedFares :)
